### ISSUE TITLE
Auto unpack not working

### ISSUE THREAD

**Issue by airy52** [crazy-max/docker-rtorrent-rutorrent#138] opened 2021-12-27 04:20 UTC
I can unpack manually but auto unpack is not working. I have "enable autounpacking" checked with /.*/ as the filter and directory left blank for torrent's current directory. I did not like the default behavior of moving torrents to different temporary/finished/etc directories as it caused problems with sonarr/radarr so I commented out these lines:

 Move finished (no need Autotools/Automove plugin on ruTorrent)
#method.insert = d.get_finished_dir, simple, "cat=$cfg.download_complete=,$d.custom1="
#method.insert = d.move_to_complete, simple, "d.directory.set=$argument.1=; execute=mkdir,-p,$argument.1=; execute=mv,-u,$argument.0=,$argument.1=; d.save_full_session="
#method.set_key = event.download.finished,move_complete,"d.move_to_complete=$d.data_path=,$d.get_finished_dir="

and my environment variable RU_REMOVE_CORE_PLUGINS is just httprpc

Any ideas why auto unpack isn't working? Is there a place I can look for logs? rtorrent.log and rutorrent.log are basically empty, I can't find any useful logs.

**Comment by newadventure079** [comment] 2022-04-28 21:56
FWIW, autounpacking works fine for me

**Comment by CraftyClown** [comment] 2022-09-10 23:49
Are you still having this issue? I'm having exactly the same problem where manual unpacking works fine but auto unpacking doesn't
I also have the boxes left blank for the default location

**Comment by ksheyman** [comment] 2022-09-27 05:01
At least for me, it would appear that the problem is in AutoTools. I was having this problem when I had automove enabled - autounpack did not work but manual did. When I disabled automove, autounpack worked and the completed torrent was STILL moved to the /downloads/complete directory. This has to be some kind of an error or oversight. From what I can tell, there is no way to prevent it from moving the completed download, and no way to specify where to move it to other than /downloads/complete. The automove feature seems to be totally useless. And for whatever reason, if you try to use automove, it causes autounpack to not work.

**Comment by airy52** [comment] 2022-10-18 03:09
> At least for me, it would appear that the problem is in AutoTools. I was having this problem when I had automove enabled - autounpack did not work but manual did. When I disabled automove, autounpack worked and the completed torrent was STILL moved to the /downloads/complete directory. This has to be some kind of an error or oversight. From what I can tell, there is no way to prevent it from moving the completed download, and no way to specify where to move it to other than /downloads/complete. The automove feature seems to be totally useless. And for whatever reason, if you try to use automove, it causes autounpack to not work.

I'm not using any autotools, automove or autolabel. Sonarr and Radarr have TV and Movies downloaded to their respective directory and then they make a symlink/softlink to my meda directory, so I can have it in my seed directory and organized/renamed in my media directory without taking up 2x the space. It's really strange that it doesn't unpack but I don't know how to troubleshoot it. I have the directory set to empty and filter set to /.*/

Any code oriented individuals have any ideas on how to figure this out? Maybe I will just start from scratch, but its going to be a pain re-importing and verifying thousands of torrents so I'd like to avoid that. For now I'm just avoiding trackers that use compressed formats but it really limits my options.

**Comment by airy52** [comment] 2022-10-18 17:49
UPDATE: I changed the filter to * from /.*/ and it appears to be unpacking now, neat. So I just went back and looked and it has changed the filter back to /.*/. So nothing makes sense but somehow its working.

**Comment by crazy-max** [comment] 2022-12-30 06:33
Closing since it seems to be solved. As it's related to rtorrent an not the image itself, I suggest to open an issue on the upstream repo instead.

**Closed by crazy-max** 2022-12-30 06:33 UTC
Labels: :question: question
